CREATE TABLE IF NOT EXISTS `MARKET_ORDERS` (
  `INDX` int(11) NOT NULL,
  `ORDER_TYPEE` varchar(31),
  `TRADING_ID` int(11) NOT NULL,
  `ORDER_REFERENCE` varchar(50) DEFAULT NULL,
  `TIMESTAMP` datetime NOT NULL,
  `TYPE` varchar(10) NOT NULL,
  `AMOUNT_COINS` float DEFAULT NULL,
  `AMOUNT_CRYPTOCOINS` float DEFAULT NULL,
  `EXCHANGE_RATE` float NOT NULL,
  `FEE` float NOT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `MANUALLY_CREATED` tinyint(1) NOT NULL,
  `RETRY_COUNT` int(11) NOT NULL,
  PRIMARY KEY (`INDX`,`TRADING_ID`,`TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `MARKET_ORDERS`
--

