DELETE FROM FUNDS;
DELETE FROM FUND_HISTORY;
DELETE FROM WALLET;
DELETE FROM CRYPTOCOIN_HISTORY;
DELETE FROM TRADINGS;
DELETE FROM TRADE_PAIR;
DELETE FROM TRADING_SITES;
DELETE FROM CURRENCIES;
DELETE FROM TRENDS;

