DELETE FROM MARKET_ORDERS;
DELETE FROM LIMIT_ORDERS;
DELETE FROM CRYPTOCOIN_TRENDS;
DELETE FROM SIGNALS;
DELETE FROM LOGGING;
DELETE FROM PARAMETERS;
DELETE FROM FUNDS;
DELETE FROM FUND_HISTORY;
DELETE FROM WALLET;
DELETE FROM CRYPTOCOIN_HISTORY;
DELETE FROM TRADINGS;
DELETE FROM TRADE_PAIR;
DELETE FROM TRADING_SITES;
DELETE FROM CURRENCIES;
DELETE FROM MACD;
DELETE FROM TRENDS;
DELETE FROM TRADE_CONDITIONS;
DELETE FROM TRADE_CONDITION_TYPES;
DELETE FROM TRADE_RULES;


